import { RiskLevel } from '@prisma/client';

interface Analysis {
  id: string;
  overallSummary: string;
  contentCoverageScore: number;
  contentCoverageJustification: string;
  contentCoverageQuotes: string | null;
  facilitationQualityScore: number;
  facilitationQualityJustification: string;
  facilitationQualityQuotes: string | null;
  protocolSafetyScore: number;
  protocolSafetyJustification: string;
  protocolSafetyQuotes: string | null;
  safetyFlag: boolean;
  riskLevel: RiskLevel;
  riskQuote: string | null;
  riskReason: string | null;
  modelUsed: string;
  processingTime: number;
}

interface AnalysisCardProps {
  analysis: Analysis;
}

// function ScoreIndicator({
//   score,
//   labels,
//   max = 3,
// }: {
//   score: number;
//   labels: string[];
//   max?: number;
// }) {
//   return (
//     <div className="flex items-center gap-3">
//       {/* star rating indicators */}
//       <div className="flex gap-1">
//         {[...Array(max)].map((_, i) => (
//           <div
//             key={i}
//             className={`h-6 w-6 rounded-full flex items-center justify-center transition-colors ${
//               i < score ? 'bg-gray-700 text-white' : 'bg-gray-200 text-gray-400'
//             }`}
//           >
//             <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
//               <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
//             </svg>
//           </div>
//         ))}
//       </div>
//       {/* score label */}
//       <div className="flex items-center gap-2">
//         <span className="text-sm font-semibold text-gray-900">
//           {labels[score - 1]}
//         </span>
//         <span className="text-xs text-gray-500">
//           ({score}/{max})
//         </span>
//       </div>
//     </div>
//   );
// }

type ScoreIndicatorProps = {
  score: number;
  labels: string[];
  max?: number;
};

export function ScoreIndicator({
  score,
  labels,
  max = 3,
}: ScoreIndicatorProps) {
  return (
    <div className="flex items-center gap-3">
      {/* star rating indicators */}
      <div className="flex gap-1">
        {[...Array(max)].map((_, i) => {
          const starValue = i + 1;
          const isFilled = starValue <= score;

          return (
            <svg
              key={i}
              className="h-6 w-6 transition-colors"
              viewBox="0 0 20 20"
              fill={isFilled ? '#1f2937' : 'white'}
              stroke="black"
              strokeWidth={1.5}
            >
              <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
            </svg>
          );
        })}
      </div>

      {/* score label */}
      <div className="flex items-center gap-2">
        <span className="text-sm font-semibold text-gray-900">
          {labels[score - 1]}
        </span>
        <span className="text-xs text-gray-500">
          ({score}/{max})
        </span>
      </div>
    </div>
  );
}

function QuoteBox({ quotes }: { quotes: string | null }) {
  if (!quotes) return null;

  const quoteList = quotes.split('\n').filter((q) => q.trim());

  return (
    <div className="mt-2 bg-gray-50 border border-gray-200 rounded p-3 space-y-2">
      <p className="text-xs font-medium text-gray-600">Supporting Evidence:</p>
      {quoteList.map((quote, idx) => (
        <p
          key={idx}
          className="text-xs text-gray-700 italic pl-3 border-l-2 border-gray-300"
        >
          &ldquo;{quote.replace(/^"|"$/g, '')}&rdquo;
        </p>
      ))}
    </div>
  );
}

export default function AnalysisCard({ analysis }: AnalysisCardProps) {
  const isRisk = analysis.riskLevel === 'RISK';
  const hasSafetyViolation = analysis.safetyFlag;

  return (
    <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
      <div
        className={`px-6 py-4 ${isRisk ? 'bg-red-500' : hasSafetyViolation ? 'bg-orange-600' : 'bg-indigo-600'}`}
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold text-white">
            AI Session Analysis
          </h2>
        </div>
        <p className="mt-1 text-sm text-white/90">
          Generated by {analysis.modelUsed} • {analysis.processingTime}ms
        </p>
      </div>

      <div className="p-4 space-y-6">
        {/* risk assessment - CRITICAL */}
        {isRisk && (
          <div className="bg-red-50 border-2 rounded-lg p-4">
            <div className="flex items-start gap-3">
              <div className="flex-1">
                <h3 className="text-sm font-bold text-red-900 uppercase tracking-wide">
                  RISK DETECTED
                </h3>
                <p className="mt-2 text-sm text-red-800 font-medium">
                  {analysis.riskReason}
                </p>
                {analysis.riskQuote && (
                  <div className="mt-3 bg-white border border-red-100 rounded p-3">
                    <p className="text-xs font-medium text-red-900 mb-1">
                      Concerning Quote:
                    </p>
                    <p className="text-sm text-red-800 italic">
                      &ldquo;{analysis.riskQuote}&rdquo;
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {!isRisk && (
          <div className="bg-green-50 border border-green-200 rounded-lg p-4">
            <div className="flex items-center gap-2">
              <svg
                className="h-5 w-5 text-green-600"
                fill="currentColor"
                viewBox="0 0 20 20"
              >
                <path
                  fillRule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                  clipRule="evenodd"
                />
              </svg>
              <span className="text-sm font-medium text-green-900">
                No safety concerns detected
              </span>
            </div>
          </div>
        )}

        {/* overall summary */}
        <div>
          <h3 className="text-sm font-semibold text-gray-900 mb-2 flex items-center gap-2">
            <span>Overall Assessment</span>
          </h3>
          <p className="text-sm text-gray-700 leading-relaxed bg-gray-50 p-3 rounded border border-gray-200">
            {analysis.overallSummary}
          </p>
        </div>

        {/* session metrics */}
        <div className="space-y-4">
          <h3 className="text-sm font-semibold text-gray-900 border-b pb-2">
            Shamiri Quality Index
          </h3>

          {/* metric 1: content coverage */}
          <div className="space-y-2 p-4 rounded-lg border border-blue-100">
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <h4 className="text-sm font-semibold text-gray-900 mb-1">
                  Metric 1: Content Coverage
                </h4>
                <p className="text-xs text-gray-600 mb-3">
                  Did the Fellow teach the material?
                </p>
                <ScoreIndicator
                  score={analysis.contentCoverageScore}
                  labels={['Missed', 'Partial', 'Complete']}
                />
              </div>
            </div>
            <p className="text-xs text-gray-700 mt-3 leading-relaxed">
              {analysis.contentCoverageJustification}
            </p>
            <QuoteBox quotes={analysis.contentCoverageQuotes} />
          </div>

          {/* metric 2: facilitation quality */}
          <div className="space-y-2 p-4 rounded-lg border border-purple-100">
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <h4 className="text-sm font-semibold text-gray-900 mb-1">
                  Metric 2: Facilitation Quality
                </h4>
                <p className="text-xs text-gray-600 mb-3">
                  How did the Fellow deliver the material?
                </p>
                <ScoreIndicator
                  score={analysis.facilitationQualityScore}
                  labels={['Poor', 'Adequate', 'Excellent']}
                />
              </div>
            </div>
            <p className="text-xs text-gray-700 mt-3 leading-relaxed">
              {analysis.facilitationQualityJustification}
            </p>
            <QuoteBox quotes={analysis.facilitationQualityQuotes} />
          </div>

          {/* metric 3 - protocol safety */}
          <div className="space-y-2 p-4 rounded-lg border">
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <h4 className="text-sm font-semibold text-gray-900 mb-1 flex items-center gap-2">
                  Metric 3: Protocol Safety
                  {hasSafetyViolation && (
                    <span className="text-xs bg-orange-200 text-orange-900 px-2 py-0.5 rounded-full font-bold">
                      VIOLATION
                    </span>
                  )}
                </h4>
                <p className="text-xs text-gray-600 mb-3">
                  Did the Fellow stay within boundaries?
                </p>
                <ScoreIndicator
                  score={analysis.protocolSafetyScore}
                  labels={['Violation', 'Minor Drift', 'Adherent']}
                />
              </div>
            </div>
            <p className="text-xs text-gray-700 mt-3 leading-relaxed">
              {analysis.protocolSafetyJustification}
            </p>
            <QuoteBox quotes={analysis.protocolSafetyQuotes} />
          </div>
        </div>

        {/* overall score */}
        <div className="pt-4 border-t border-gray-200">
          <div className="flex items-center justify-between">
            <span className="text-sm font-semibold text-gray-900">
              Average Score
            </span>
            <div className="text-right">
              <span className="text-xl font-bold text-gray-900">
                {(
                  (analysis.contentCoverageScore +
                    analysis.facilitationQualityScore +
                    analysis.protocolSafetyScore) /
                  3
                ).toFixed(1)}
              </span>
              <span className="text-sm text-gray-600"> / 3.0</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
